version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - server
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=api
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AUTH_SECRET=276bc07e3004220dbdecfde4960413da0b17d8b70573a30b74240849c0785a9e
    restart: unless-stopped
    networks:
      - app-network


networks:
  app-network:
    driver: bridge